version: '3'
services:
  db:
    image: "postgres"
    container_name: database
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root  
    volumes:
      - .:/go/src/    
    ports:
      - "5432:5432"
    networks:
      - fullstack 

  app:
    build: .
    container_name: api
    environment:
      - DB_TYPE=postgres
      - DSN=dbname=root sslmode=disable user=root password=root host=database
      - DB_TYPE_TEST=sqlite3
      - DSN_TEST=
      - ENV=dev
      - DEBUG=true
      - AUTO_MIGRATE_DB=true
    restart: on-failure
    volumes:
      - .:/go/src/
    ports:
      - "8080:8080"
    networks:
      - fullstack
    depends_on:
      - db

networks:
  fullstack:
    driver: bridge